# API version for Deployment resources
apiVersion: apps/v1
# Specifies this is a Deployment object
kind: Deployment
metadata:
  # Name of the Deployment
  name: k8sapp
  # Namespace where the Deployment will be created
  namespace: default
spec:
  # Number of pod replicas to run
  replicas: 1
  selector:
    matchLabels:
      # Selects pods with label 'app: k8sapp'
      app: k8sapp
  template:
    metadata:
      labels:
        # Labels to apply to the pods created by this Deployment
        app: k8sapp
    spec:
      containers:
      - # Name of the container
        name: k8sapp
        # Docker image to use for the container
        image: k8sapp:v1
        ports:
        - # Port exposed by the container
          containerPort: 5000
