# API version for Service resources
apiVersion: v1
# Specifies this is a Service object
kind: Service
metadata:
  # Name of the Service
  name: k8sapp-service
  # Namespace where the Service will be created
  namespace: default
spec:
  selector:
    # Selects pods with label 'app: k8sapp'
    app: k8sapp
  # Service type; exposes the Service on a cluster-internal IP
  type: ClusterIP
  ports:
  - # Port exposed by the Service (inside the cluster)
    port: 5000
    # Port on the Pod to forward traffic to
    targetPort: 5000
    # Protocol used for the Service
    protocol: TCP